apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo-service
    app: node-mongo-app
spec:

  ports:
    - port: 3306
      targetPort: 3306
  selector:
    appName: node-mongo-app
    tier: backend